-- AlterEnum
ALTER TYPE "ListingFieldType" ADD VALUE 'LINEAR_SCALE';
ALTER TYPE "ListingFieldType" ADD VALUE 'MULTIPLE_CHOICE_GRID';
ALTER TYPE "ListingFieldType" ADD VALUE 'CHECKBOX_GRID';
ALTER TYPE "ListingFieldType" ADD VALUE 'DATE';
ALTER TYPE "ListingFieldType" ADD VALUE 'TIME';
ALTER TYPE "ListingFieldType" ADD VALUE 'FILE_UPLOAD';
